"use strict";
module.exports = {
    // game parameters
	DEFAULT_PLAYER_RADIUS: 24, 
    DEFAULT_PLAYER_COLOR: 'red',
    DEFAULT_PLAYER_SPEED: 3,
    DEFAULT_PLAYER_VISION: 1e10,
    DEFAULT_PLAYER_RELOADTIME: 500,  // ms
    DEFAULT_PLAYER_HP: 3,

    DEFAULT_MAP_WIDTH: 2000,
    DEFAULT_MAP_HEIGHT: 1500,

    DEFAULT_MAP_MAX_POWERUPS: 10,
    DEFAULT_POWERUP_HEIGHT: 14,
    DEFAULT_POWERUP_WIDTH: 8,

    DEFAULT_PROJECTILE_SPEED: 5,
    DEFAULT_PROJECTILE_RADIUS: 6,
    DEFAULT_PROJECTILE_RANGE: 500,

    POWER_NONE: 0,
    POWER_CANNON: 1,

    PLAYER_RADIUS_PER_HP:  8,
    //PROJECTILE_RADIUS_PER_HP: 2
    PROJECTILE_TO_PLAYER_RADIUS: 0.2
};
